name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Update to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Update to v3
        with:
          node-version: '20' # Ensure Node.js 20 is used

      - name: Install dependencies
        run: npm install

      - name: Setup Google Cloud Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > $HOME/gcloud-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json" >> $GITHUB_ENV

      - name: Set Neon Database URL
        run: echo "NEON_DATABASE_URL=${{ secrets.NEON_DATABASE_URL }}" >> $GITHUB_ENV

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Update to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist