name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Setup Google Cloud Credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > $HOME/gcloud-key.json
          echo "Google Cloud Credentials:"
          cat $HOME/gcloud-key.json
          if ! jq . $HOME/gcloud-key.json > /dev/null; then
            echo "Invalid JSON in GOOGLE_CREDENTIALS"
            exit 1
          fi

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json" >> $GITHUB_ENV

      - name: Set Neon Database URL
        run: echo "NEON_DATABASE_URL=${{ secrets.NEON_DATABASE_URL }}" >> $GITHUB_ENV

      - name: Build the project
        run: node build.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist